name: Build and Upload on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Package the extension
      run: npx vsce package

    - name: Upload VSIX to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./vscode-titlebar-colour/titlebar-colour-*.vsix
        asset_name: titlebar-colour.vsix
        asset_content_type: application/octet-stream
